### ISSUE TITLE
能更新下QQ的代码吗？

### ISSUE THREAD

**Issue by yorkwang** [CCSH/SHChatMessageUI#1]
感谢开源这套组件，QQUI有些动画不是很平滑和一些小bug，能更新到最新吗？

**Comment by CCSH** [comment]
现在没时间 你的问题在哪里 是聊天内容还是输入框的问题

**Comment by yorkwang** [comment]
emoji和键盘切换时，动画有些不平滑；photo picker有内存泄露；录音时，voice的音量动画没有；输入框没有自增高；还有聊天内容的有些动画也有些不平滑。目前就发现这些。

**Comment by CCSH** [comment]
1、emoji和键盘切换时，动画有些不平滑
可以看一下微信版的那个，将表情键盘作为inputview 平滑了
2、photo picker有内存泄露
那个自己看着改一下吧。。
3、录音时，voice的音量动画没有
计算声波有问题可能，也看一下微信版的
4、输入框没有自增高
刚才写了一个加上去了 微信版
5、还有聊天内容的有些动画也有些不平滑。目前就发现这些。
看具体的 最好还是看微信版的

因为大多数是微信那种样式 所以之前重写了微信版的

**Comment by yorkwang** [comment]
好的，谢谢了
