### ISSUE TITLE
在10.3.1系统中释放内存崩溃

### ISSUE THREAD

**Issue by kuangjunjie** [CCSH/SHChatMessageUI#10]
不修改代码情况下,聊天页面没有释放
添加如下代码, 控制器释放,但是崩溃了.
- (void)viewDidDisappear:(BOOL)animated{
    [super viewDidDisappear:animated];
    self.selectCell = nil;
    self.chatInputView.delegate = nil;
    self.chatInputView.supVC = nil;
}
错误信息
2019-11-21 15:06:21.441 SHChatUI[14784:111844] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7fe4f1c1bf90 of class SHMessageInputView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x61800022d160> (
<NSKeyValueObservance 0x618000059560: Observer: 0x7fe4f1c1bf90, Key path: frame, Options: <New: YES, Old: YES, Prior: NO> Context: 0x0, Property: 0x618000059a40>
)'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010d50cb0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010cb49141 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010d575625 +[NSException raise:format:] + 197
	3   Foundation                          0x000000010c684b53 NSKVODeallocate + 294
	4   libobjc.A.dylib                     0x000000010cb5e2fa _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 866
	5   UIKit                               0x000000010e84a2f7 -[UIView dealloc] + 1841
	6   libobjc.A.dylib                     0x000000010cb5e2fa _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 866
	7   CoreFoundation                      0x000000010d45be96 _CFAutoreleasePoolPop + 22
	8   CoreFoundation                      0x000000010d497aec __CFRunLoopRun + 2172
	9   CoreFoundation                      0x000000010d497016 CFRunLoopRunSpecific + 406
	10  GraphicsServices                    0x000000011362ea24 GSEventRunModal + 62
	11  UIKit                               0x000000010e7b5134 UIApplicationMain + 159
	12  SHChatUI                            0x000000010c40fa70 main + 112
	13  libdyld.dylib                       0x000000011080865d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

好像是说一个KVO还在监听,但是没有找到,不知如何下手

**Comment by kuangjunjie** [comment]
已经解决了
- (void)dealloc{
    @try {
        [self.chatInputView removeObserver:self forKeyPath:@"frame"];
    }
    @catch(NSException *exception) {
        NSLog(@"--%@", exception);
    }
    [[NSNotificationCenter defaultCenter] removeObserver:self];
}

**Comment by lifewahaha** [comment]
kkk

**Comment by lifewahaha** [comment]
大兄弟是因为输入框有个循环引用问题，把strong改成weak就行了。
