### ISSUE TITLE
语音网络获取缓存处理有没有好的方法

### ISSUE THREAD

**Issue by Lunaict** [CCSH/SHChatMessageUI#11]

**Comment by CCSH** [comment]
最早看微信是 消息进来 判断是语音消息(有特殊资源消息也这么处理)，则开始开一个下载线程去下载，音频采用amr 大概最多几十k，到界面上基本上已经下载完毕，为了以防万一在用户点击时，再去判断本地缓存，没有则下载，有则播放本地
