### ISSUE TITLE
音频播放SHAudioPlayerHelper.m，有个参数有疑问。

### ISSUE THREAD

**Issue by ReefJones** [CCSH/SHChatMessageUI#15]
初始化各个参数
- (void)managerAudioWithFileArr:(NSArray *)fileArr isClear:(BOOL)isClear; 
在这个方法内 _playingIndex = 1; 导致音频获取不到文件名，改成_playingIndex = 0;就可以了。

**Comment by CCSH** [comment]
之前代码开始都是1开始的 作为定位 后面修改的时候为了对数组好处理从0开始了，最新代码都是0，有其他问题建议查看最新代码
