### ISSUE TITLE
发文字+表情时，两行字长一点，下一行里有个表情，这个第一行的字就会被削顶了

### ISSUE THREAD

**Issue by ReefJones** [CCSH/SHChatMessageUI#16]
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-12 at 15 47 04](https://user-images.githubusercontent.com/17866310/117938594-bd25c480-b2f6-11eb-89ab-0f114c1dee71.png)

**Comment by CCSH** [comment]
textAttachment.bounds = CGRectMake(0, -3, height, height); 表情键盘那个组件里面调整下大小

**Comment by CCSH** [comment]
![Uploading WX20220128-104501@2x.png…]()
高度偏高了 加了行间距 后面有时间再看
