### ISSUE TITLE
这个时间怎么在初始化的时候设置会崩溃呢？

### ISSUE THREAD

**Issue by xhr4469** [CCSH/SHChatMessageUI#18]
- (SHMessage *)getTextMessage
- 比如在这里设置时间 message.sendTime = @"2020-08-08-08-08-08-958";   会崩溃

**Comment by CCSH** [comment]
应该不会崩溃 就是获取了时间 打断点看下，我这边没有遇到 这个方法是测试方法 实际使用中 看下
