### ISSUE TITLE
微信项目运行都报错的呀

### ISSUE THREAD

**Issue by DongfengWang123** [CCSH/SHChatMessageUI#2]
项目直接运行的时候都报 linker command failed with exit code 1 (use -v to see invocation)这样的错误

**Comment by CCSH** [comment]
刚看了一下bitcode错误 关了就好了

**Comment by DongfengWang123** [comment]
谢谢,终于遇见大神的杰作了.以后有时间的话可以再增加一个刷礼物的功能就更加完美了.

**Comment by CCSH** [comment]
这是什么需求。。。直播么，如果是消息的话里面拓展起来很方便的

**Comment by DongfengWang123** [comment]
奥,知道了.我好好看看,已给你完美的点赞了

**Comment by CCSH** [comment]
谢谢
