### ISSUE TITLE
咨询问题

### ISSUE THREAD

**Issue by zx-ljn** [CCSH/SHChatMessageUI#22]
你这个和聊天端服务器进行连接的配置放在哪里了

**Comment by CCSH** [comment]
我去掉了，实际业务可能接三方IM比较多，XMPP自己写的用的少

**Comment by zx-ljn** [comment]
我们现在要自己写XMPP，想用你这个界面的话，难度很大吧

**Comment by zx-ljn** [comment]
只使用XMPP的SDK，然后界面自己画

**Comment by CCSH** [comment]
聊天数据放后台就不大，xmpp写个工具类就可以，然后用通知发送到界面展示，要是写的比较细那界面有两套展示数据逻辑，什么时候用数据库展示，什么时候用通知过来的展示

**Comment by CCSH** [comment]
再细化一点就是离线消息并发，界面通知优化这些，不能频繁刷新界面

**Comment by zx-ljn** [comment]
聊天数据首先是从后台获取。。那如果你这个不连接服务器，怎么实时发消息给对方，怎么添加对方好友什么的呢

**Comment by CCSH** [comment]
xmpp可以实现长连接的。添加好友可以用xmpp的花名册，也可以用你们服务器自己的用户信息

**Comment by CCSH** [comment]
通信这里没有好又不好友的概念，只要jid拼接上就能发消息

**Comment by zx-ljn** [comment]
你的jid在哪里配置的啊

**Comment by CCSH** [comment]
你还是先看下xmpp基础的东西吧，我这只有UI

**Comment by zx-ljn** [comment]
你的意思是和你的能融合起来，是吗

**Comment by zx-ljn** [comment]
我现在没有任何头绪，只跑起来了xmpp一个单聊的demo，然后和我们后台的服务器连上了并且发成功了消息

**Comment by zx-ljn** [comment]
但是那个demo界面是真的太粗糙了哈哈

**Comment by CCSH** [comment]
我这代码只有展示，具体的业务自己接 通信服务还是数据库展示逻辑

**Comment by CCSH** [comment]
通信这里，很多细节一时半会都说不明白，应该有很多人封装好的xmpp、mqtt工具类，自己拿过来就能用的，你找找

**Comment by zx-ljn** [comment]
我看到你用了挺多cell，有没有一个所有消息都公用的cell

**Comment by CCSH** [comment]
多种cell 但是继承于一个基础的cell  SHMessageTableViewCell

**Comment by zx-ljn** [comment]
我看你的界面满足我们的需求

**Comment by CCSH** [comment]
多种cell的 性能好 可拓展性也强 阅读起来也清晰 自己改起来也方便

**Comment by zx-ljn** [comment]
好的，十分感谢

**Comment by zx-ljn** [comment]
麻烦问一下，你那个消息的已读未读是什么逻辑呢？


我将聊天记录存在了本地，然后将和其中一个人的聊天消息属性isRead设置成已读，渲染发现聊天历史页面全不正常了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CCSH/SHChatMessageUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月12日(星期三) 中午11:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CCSH/SHChatMessageUI] 咨询问题 (Issue #22)





 
多种cell的 性能好 可拓展性也强 阅读起来也清晰 自己改起来也方便

**Comment by CCSH** [comment]
一般是展示到界面就是已读，具体看你业务，要同步的话还需要发一条im消息告诉对方更改ta本地的消息状态，自己研究下吧
