### ISSUE TITLE
点击表情或者更多按钮之后，再点输入框键盘不弹出

### ISSUE THREAD

**Issue by SUWW** [CCSH/SHChatMessageUI#24]
希望继续可以完善：点击表情或者更多按钮之后，再点输入框键盘不弹出

**Comment by CCSH** [comment]
1、早期需求就是这样的系统键盘跟表情键盘都有光标调整，需要点击表情切换才可以
2、至于你说的多媒体点击后，点击输入框键盘不弹出未复现

**Comment by SUWW** [comment]
> 1、早期需求就是这样的系统键盘现跟表情键盘都有调整，需要点击表情切换才可以 2、至于你说的多媒体点击后，点击输入框键盘不弹出未复

十分感谢你的回复，点击多媒体之后，再点击输入框，是正常的。之前是因为我这边冲突导致的。你说的这个：1、早期需求就是这样的系统键盘现跟表情键盘都有调整，需要点击表情切换才可以。我想要改为点击了表情之后，我再点输入框就会自动切换到文本输入的，这个我该如何改动？

**Comment by CCSH** [comment]
好久的项目了，都不怎么写原生了，你试试输入框加一个点击方法然后设置输入类型为SHInputViewType_text试试
