### ISSUE TITLE
加载本地图片 滑动卡顿

### ISSUE THREAD

**Issue by HankMax** [CCSH/SHChatMessageUI#3]
我看你各种消息类型用的复用同一个cell，只是内部控制消息类型隐藏显示，这样是不是会造成卡顿？

**Comment by CCSH** [comment]
还可以吧！多种类型 多种cell 复用效果不明显

**Comment by CCSH** [comment]
如果你想便于管理的话，可以考虑不同类型使用不同的cell

**Comment by HankMax** [comment]
卡顿原因找到了 因为你读取本地添加的图片用的imageWithContentsOfFile这种方式不会缓存图片，滑动列表会反复进行IO操作造成卡顿

**Comment by CCSH** [comment]
我这个是为了放在bundle 便于管理这么写的，你可以拿出来修改我读去图片的方法，我里面有个统一的方法。
刚才我增加了cell创建，一种聊天类型对应一种cell，两种方式都保留了，自己看用哪个
