### ISSUE TITLE
发送完一天消息，在键盘还没消失是，滑动屏幕，键盘消失，然而tableview的cell有跳动，而且还是很明显，

### ISSUE THREAD

**Issue by wongwander** [CCSH/SHChatMessageUI#5]

**Comment by CCSH** [comment]
键盘消失有改变聊天界面frame动画，可能有冲突了动画 有时间的话我看看

**Comment by CCSH** [comment]
最近优化了下代码，包括动画，输入框细节，看下还有这个问题么

**Comment by bigcoww** [comment]
cell还是会跳动,在发送完消息,滑动屏幕,键盘消失,cell跳动很厉害

**Comment by bigcoww** [comment]
_chatTableView.estimatedRowHeight = 0; 加上默认高度

**Comment by ninagaogao** [comment]
[UIView performWithoutAnimation:^{
        cell.messageFrame = messageFrame;
 }];
